### ISSUE TITLE
todomvc example is broken

### ISSUE THREAD

**Issue by maks83** [joelburget/react-haskell#15]
~/react-haskell/example/todomvc$ hastec todomvc.hs

todomvc.hs:133:11:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:134:18:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:135:32:
    Not in scope: ‘getState’
    Perhaps you meant ‘getStyle’ (imported from Haste)

todomvc.hs:137:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:138:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:139:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:140:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:141:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:142:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:144:20:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:146:26:
    Not in scope: ‘getState’
    Perhaps you meant ‘getStyle’ (imported from Haste)

todomvc.hs:148:9:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:149:14:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:150:20:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:151:20:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:152:20:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:153:20:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:154:20:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:155:21:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:156:21:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:158:16:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:159:16:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:164:13:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:166:26:
    Not in scope: ‘getState’
    Perhaps you meant ‘getStyle’ (imported from Haste)

todomvc.hs:167:14:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:168:16:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:168:36:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:169:16:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:170:16:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:173:13:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:175:16:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:176:23:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:177:26:
    Not in scope: ‘getState’
    Perhaps you meant ‘getStyle’ (imported from Haste)

todomvc.hs:185:11:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:191:17:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:192:17:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:195:16:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:196:23:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:200:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:203:12:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

todomvc.hs:205:14:
    Not in scope: type constructor or class ‘StatefulReact’

todomvc.hs:207:26:
    Not in scope: ‘getState’
    Perhaps you meant ‘getStyle’ (imported from Haste)

todomvc.hs:208:14:
    Not in scope: ‘<!’
    Perhaps you meant one of these:
      ‘!’ (imported from Haste.JSON), ‘<’ (imported from Prelude),
      ‘$!’ (imported from Prelude)

**Comment by joelburget** [comment]
Fixed by 9051638f0ea6ae9b7abc490328b70edb2546ea0b
