### ISSUE TITLE
Functor instance for ReactNode

### ISSUE THREAD

**Issue by bergey** [joelburget/react-haskell#22]
It looks as though `ReactNode` admits a `Functor` instance, which would use `LocalNode` but pick the `insig -> sig` function at the use site, rather than a type-based default.  Is there a reason this instance is not provided?  Would you accept a PR?

The `Functor` laws aren't exactly obeyed, because you can count how many times `fmap` has been applied.  I'm not sure this matters, since the constructors aren't exported.  I'd be fine with some `sigMap` though, with the same type but without the laws.

**Comment by joelburget** [comment]
> Is there a reason this instance is not provided?

I just haven't needed it. Actually, I'm curious what you plan to use it for.

> Would you accept a PR?

Absolutely.

Let's start with `sigMap`, since, as you say, the laws are not followed. After that, will think about making a `Functor` instance.
